### ISSUE TITLE
Youtube embed will cause please-wait not to close

### ISSUE THREAD

**Issue by teolemon** [Pathgather/please-wait#14] opened 2015-09-10 18:17 UTC
Embedding 
<iframe id="ytplayer" type="text/html" width="640" height="390" src="https://www.youtube.com/embed?listType=search&autoplay=0&list=powerpoint" frameborder="0"/>

prevents Please Wait from closing.

It seems that using asynchronous Youtube API solves it.

**Comment by NevilleS** [comment] 2015-09-11 04:08
Hmm, I'm not sure what you mean?

**Comment by NevilleS** [comment] 2015-09-16 14:25
Hey @teolemon, can you clarify this at all? I'm not sure how to help right now since I don't understand the issue...

**Comment by qrtise** [comment] 2015-09-16 16:23
We use embedded youtube in our App and please wait does not have an issue.
The only issue is with the old Android browser no-name no standard thing they did on all new browsers works fine with Youtube embedded

**Comment by NevilleS** [comment] 2015-09-16 16:28
I'm going to close this for now, since I don't see a way to help. Please re-open if you can explain the issue (with a way to reproduce, ideally), though!

**Closed as completed by NevilleS** 2015-09-16 16:28 UTC

**Comment by teolemon** [comment] 2015-10-02 14:58
@NevilleS : Sorry for not catching up earlier. This snippet will let you reproduce the issue.

```
<iframe id="ytplayer" type="text/html" width="640" height="390" src="https://www.youtube.com/embed?listType=search&amp;autoplay=0&amp;list=Autonomie" frameborder="0"></iframe>
```
